# Different configurations for benchmarking
# Usage: docker-compose -f docker-compose-configs.yml up <service-name>

services:
  # 1. Dual-write mode (default - maximum data safety)
  go-db-dual-write:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - go-db-dual-write-data:/app/data
    restart: unless-stopped
    command: ['-data-dir', '/app/data', '-no-saves=false']
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 60s
      timeout: 5s
      retries: 2

  # 2. No-saves mode (maximum performance)
  go-db-no-saves:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - go-db-no-saves-data:/app/data
    restart: unless-stopped
    command: ['-data-dir', '/app/data', '-no-saves=true']
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 60s
      timeout: 5s
      retries: 2

volumes:
  go-db-dual-write-data:
    driver: local
  go-db-no-saves-data:
    driver: local
