services:
  go-db:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - go-db-data:/app/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 60s
      timeout: 5s
      retries: 2

volumes:
  go-db-data:
    driver: local
