services:
  go-db:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - go-db-data:/app/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/collections/health/find',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  go-db-data:
    driver: local
